### ISSUE TITLE
timeBoundary not updated on offline segment refresh

### ISSUE THREAD

**Issue by haibow** [apache/incubator-pinot#3089]
We have users using realtime+offline tables, and the offline segment is override mode, i.e. instead of appending new segments per day, segment content is replaced and pushed with the same segment name, to accommodate expected changes in upstream data. Offline table holds the aggregated results of the past n days.

We observed timeBoundary is never updated to reflect the max(secondsSinceEpoch) in the offline table. buildRoutingTable seems never called on offline segment refresh. One trigger could be `onExternalViewChange`, but on segment refresh, no new segments are added, so no externalView/idealState changes are happening: https://github.com/linkedin/pinot/blob/ee3b37eb3299985e91cba913448df70c5f30c6b9/pinot-controller/src/main/java/com/linkedin/pinot/controller/api/resources/PinotSegmentUploadRestletResource.java#L504-L518

timeBoundary is also not updated on new realtime segment since there does exist a valid, though stale, timeBoundary:
https://github.com/linkedin/pinot/blob/ee3b37eb3299985e91cba913448df70c5f30c6b9/pinot-broker/src/main/java/com/linkedin/pinot/broker/routing/HelixExternalViewBasedRouting.java#L295-L306

Have you folks seen similar scenarios or use cases like this?

**Comment by haibow** [comment]
@kishoreg could you shed some lights on this?

**Comment by kishoreg** [comment]
@haibow looking into it.

**Comment by kishoreg** [comment]
Hi @haibow, We never faced this issue because we don't override offline segments in realtime + offline mode. Before I suggest solutions, can you give us additional details about the scenario? . Is this something that happens every day or once in a while. Typically refresh use cases (where offline segments get replaced) dont have real-time.

**Comment by haibow** [comment]
@kishoreg thanks for looking into this. Data in upstream table is expected to change regularly, and there are some known issues with data source that required custom logics like dedup and backfill, so users just do the aggregation and replace the whole offline table every 6 hours. They still want fresh data in realtime table (favoring data freshness over minor incorrectness), so we end up in this mode..

**Comment by chenboat** [comment]
Hi @kishoreg the issue seems to related to the following code in the refreshSegment() function:
https://github.com/linkedin/pinot/blob/9ea11693d693d53f5712571cb1259344b5b17cc9/pinot-controller/src/main/java/com/linkedin/pinot/controller/helix/core/PinotHelixResourceManager.java#L1497-L1507

By default (i.e., if the table config does not have custom config banning direct message), the controller sends messages to servers for segment reload but it does not ask Brokers to refresh the time boundary. The else branch, on the other hand, goes through a Helix state transition to reload the segments in servers and the brokers also get notified in the process. 

So a potential fix is to let the controller also message the broker to refresh the time boundary. The broker can then compute the new time boundary: it does not need to wait all the segments get refreshed though as long as it gets a more recent time boundary. This will make the two if-else branches' behaviors about the same.

**Comment by mcvsubbu** [comment]
@haibow can we close this issue now?

**Comment by haibow** [comment]
The fix has been verified. Closing.
