### ISSUE TITLE
The segments are stored in memory

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3978]
Once segments are assigned, Pinot servers get notified via Helix to “host” the segment. The servers download the segments (as a cached local copy to serve queries) and load them into local memory. All segment data is maintained in memory as long as the server hosts that segment.

I want to know which segments are permanently loaded into the memory, and whether the memory is expensive and the data volume is large

**Comment by mcvsubbu** [comment]
All segments of a table are divided among the tenant instances that host the table. If a server has a segment to serve, it will be loaded into memory.  You can use rest commands on the controller to see the idealstate of a table, and that will indicate to you the servers that host each segment. 

It is up to you how you want to reduce cost.

You can load the segments in "HEAP" mode, you just need to make sure that the maxDirectMemory argument to the jvm is sufficiently large so that the segments are loaded without OOM errors.

You can load the segments in MMAP mode, in which case the segments are paged in from disk and Pinot lets the Operating System handle paging of segments in and out.

**Comment by ly923976094** [comment]
> All segments of a table are divided among the tenant instances that host the table. If a server has a segment to serve, it will be loaded into memory. You can use rest commands on the controller to see the idealstate of a table, and that will indicate to you the servers that host each segment.
> 
> It is up to you how you want to reduce cost.
> 
> You can load the segments in "HEAP" mode, you just need to make sure that the maxDirectMemory argument to the jvm is sufficiently large so that the segments are loaded without OOM errors.
> 
> You can load the segments in MMAP mode, in which case the segments are paged in from disk and Pinot lets the Operating System handle paging of segments in and out.

If the load model changes from HEAP to MMAP, will the segments loaded into memory be released and then read data from the disk?

**Comment by mcvsubbu** [comment]
You can read up on MMAP here : https://en.wikipedia.org/wiki/Memory-mapped_file
A segment is MMAPed as long as the server is alive and hosts the segment. If the server is restarted, it is mmaped again.

If you want to change the load mode of segments, you can update the table config with the new load mode (MMAP), and use the controller console to reload the segment (or all segments of a table). If you do this, the direct-allocated memory will be released and the segment will now be loaded in MMAP mode.

Hope this helps.

**Comment by ly923976094** [comment]
I understanding is that when I change the table's loading mode, for example, from HEAP to MMAP, I need to disable the table first, and then enable the table, and all the segments are reloaded， the direct-allocated memory will be released and the segment will now be loaded in MMAP mode.

**Comment by mcvsubbu** [comment]
You do not need to disable and re-enable table for doing this.
You can change the table config from HEAP to MMAP and either reload all segments of the table or one segment at a time.
Doing it one segment at a time is better in production scenarios since the servers need to keep both versions of the segment loaded and swap the reference while serving live traffic. You can write a script to get the segments of the table and reload each one of them

**Comment by ly923976094** [comment]
Do you mean the loading segment as shown below?
![image](https://user-images.githubusercontent.com/20608540/54796328-c53fc780-4c8a-11e9-8e27-a87464fd1a6a.png)
