### ISSUE TITLE
Filter during ingestion

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#5268]
This is a followup task to #5135

Transform functions support was added recently (b20ace081fc8566490d5e8addc211537843c8a9a). This supports simple column transformations using Groovy script, during ingestion.

Next step would be to support filtering records based on values of fields, during ingestion.

Contributions welcome

**Comment by npawar** [comment]
Initial thoughts:
We need to think about where filtering will be applied.
a) On source columns - should we fix that filtering is only on source fields?
b) On transformed columns - Should we allow a column to evaluate the transform expression, and then apply filtering?
c) Do we allow both?

The answer to the above will decide where the filtering gets applied- within RecordExtractor/RecordReader, after Expression Transformer, after all transformers (i.e. after getting default null values, data type transformation etc).

The config for this also needs to be designed.

**Comment by mcvsubbu** [comment]
It will be useful to add some use cases where this can be applied. 

Maybe this can also include sampling (e.g ingest 20% of the records at random), useful to contain volume and yet observe some trends

**Comment by reallocf** [comment]
Hey @npawar - I'm interested in helping out on this one. First initiative, so bare with me if my understanding is wrong about everything 😄. A question on the requirements:

The idea is that we should be able to filter out data during ingestion, so if we have a `pinotSchema.json` like
```
{
  "schemaName": "events",
  "dimensionFieldSpecs": [
    {
      "name": "userId",
      "dataType": "LONG",
      “transformFunction”: “Groovy({userID}, userID)”
    },
    {
      "name": "fullName",
      "dataType": "STRING",
      “transformFunction”: “Groovy({firstName+' '+lastName}, firstName, lastName)”
    },
   {
      "name": "bids",
      "dataType": "INT",
      "singleValueField": false
    },
    {
      "name": "maxBid",
      "dataType": "INT",
      "transformFunction": "Groovy({bids.max{ it.toBigDecimal() }}, bids)"
    }
  ],
  "metricFieldSpecs": [
    {
      "name": "impressions",
      "dataType": "LONG",
      “transformFunction”: “Groovy({eventType == 'IMPRESSION' ? 1: 0}, eventType)”
    },
    {
      "name": "clicks",
      "dataType": "LONG",
      “transformFunction”: “Groovy({eventType == CLICK ? 1: 0}, eventType)”
    },
    {
      "name": "cost",
      "dataType": "double"
    },
    {
      "name": "daysSinceEpoch",
      "dataType": "INT",
      “transformFunction”: “Groovy({timestamp/(1000*60*60*24)}, timestamp)”
    }
  ],
   "timeFieldSpec": {
    "incomingGranularitySpec": {
      "name": "hoursSinceEpoch",
      "dataType": "LONG",
      "timeFormat" : "EPOCH",
      "timeType": "HOURS",
      “transformFunction”: “Groovy({timestamp/(1000*60*60)}, timestamp)”
    }
  }
}
```
we would want to add a new top-level element in that json with a transformFunction  like
```
{
  "schemaName": "events",
  "filter": "Groovy({cost > 42}, cost)",
  "dimensionFieldSpecs": [
    {
      "name": "userId",
      "dataType": "LONG",
      “transformFunction”: “Groovy({userID}, userID)”
    },
    ...
  ],
  ...
}
```
Then we would apply that transformFunction either
a) On source columns - applying the rest of the transformations AFTER filtering
or
b) On transformed columns - applying the filtering after the rest of the transformations.

Is that all right? Am I on the right track?

**Comment by npawar** [comment]
Hi @reallocf ,

Thanks for taking this on!
Your understanding is right. What you proposed makes sense. My only concern with having a top level filter element, is that we won't know whether it needs to be applied on source or destination. This will not be a problem, if the expression applies just to the source or to the destination column. But what if the expression applies to both?
`timestamp >x && maxBid > y`.
Would it be better if it's defined with each column spec?
If it's top level, should we make it a list?
Should we support expressions such as `column1 + column2 > x`?

Also, have you gone through the diagram in this doc: https://docs.google.com/document/d/13BywJncHrLAFLm-qy4kfKaPxXfAg9XE5v3_fk9sGVSo/edit#heading=h.4kdvsjcasspk
It shows the various stages that the Record goes through.

**Comment by reallocf** [comment]
@npawar - thanks for the feedback! Sorry for the delayed response - got pulled into a new project at work and was really heads down for the past few days. Let me know if there's any time expectations you'd like to set here - right now I'm scoping for the next couple of weeks (I'm more or less just working off-work hours) but if y'all need this done more quickly then let me know and I'll prioritize for it or bow out and let somebody else take it.

My thoughts:
I'm thinking supporting two kinds of filtering might make the most sense: preFilter and postFilter. Pre-filtering is nice because it means, if the source row doesn't fit the filter, it can remove it without having to calculate any of the derived values. Post-filtering is nice because it allows means that any logic embedded in one of the columns doesn't have to be duplicated when calculating it for the filter (like in your example, you could just put the `maxBid` logic in a preFilter and then have that be a part of the conditional logic, but you're then duplicating that work for the actual column calculation). From an interface perspective, this also makes it slightly more sensible I think.

If we made it column-specific, that makes defining filters across columns awkward. Maybe we don't want to support them? There might be a performance improvement if we have a filter on a derived column - if that column's calculation completes early and is filtered out, it could skip the execution of other derived columns - but that seems like it might be optimizing for a very specific use case. We could also add this later if we think it'll be useful in the future.

For top-level filters being a column, someone _could_ just throw everything into a single `Groovy({column1 + column2 + ... + columnN > x}, column1, column2, ..., columnN)`. For multiple different conditions one could use `&&`. There might be a bit more clarity with having it be a list of multiple conditionals, but we might take a slight performance hit when executing the additional Groovy scripts.

Yeah, my vote is definitely for supporting expressions with multiple columns. But, I don't know the internals of the code really at all yet - do you think just focusing on a column-based approach would make more sense from an implementation perspective?

Read through the doc - very nice! :)

**Comment by kishoreg** [comment]
Great discussion so far and valid points. My take is filtering should not even be part of schema definition. This is more of an ingestion config which is part of the table config. should we move it to table config?

The challenges mentioned by @npawar such as pre-filter vs post filter etc still remain. I agree with supporting filtering across multiple columns.

Today source field name extractor is looking at the schema but its possible that we look at the filter spec as well to compute the list of fields to extract from source.

Another option is to add a boolean to fieldSpec isTransient=true  which means we just extract it from source but not store in Pinot.

**Comment by reallocf** [comment]
Good idea @kishoreg - having filtering be part of the table config does seem like it would make more sense, especially if we're defining them to being across multiple columns. Based on the table config definitions here: https://docs.pinot.apache.org/pinot-components/table do you think it's worth adding a new top-level `filter` field? Or would it be better to nest it somewhere? Will there be future ingestion-related configs that we could all group under an `ingestConfig` or something?

Oh yeah, I hadn't thought about transient fields. Is there a way that we can infer transient fields so they don't have to be handled explicitly? Probably not, because we'd lose type information... I guess the other option would be to create a `transientFieldSpecs` list in the schema definition. These also could be used for other transform functions.

But now we're blowing scope quite a bit (though good for future work! 😄). In order to keep this small and achievable, what do y'all think I should start with @npawar @kishoreg ?
1) Pre-filter/post-filter/both? I have a feeling pre-filter might be more in line with how transform functions work today, so maybe start there and we can add post-filtering in the future?
2) Define in table config or schema definition? If defining in table config, what top-level field name should we have it under? If defined in the schema definition, should it be column-based or top-level? I think my preference here is for table config, but would love to hear @npawar 's thoughts on that
3) Only handle added fieldSpecs for now? Or also handle transient fieldSpecs? My preference would be for the former, though handling transient fieldSpecs more broadly does sound interesting.
4) Should we have a list of filter expressions, or a single expression?

Also, does it sound like something along these lines would be useful for LinkedIn/your company @kishoreg ?

**Comment by npawar** [comment]
Design proposal: https://docs.google.com/document/d/1Cahnas3nh0XErETH0KHLaecN6xCnRVYWNKO3rDn7qcI/edit#
