### ISSUE TITLE
Support toWeek/toMonth/toYear in datetimeConvertUdf

### ISSUE THREAD

**Issue by xiangfu0** [apache/incubator-pinot#5704]
Need to support this functionality in datetimeConvertUdf. This function should be able to convert time to the first day of corresponding week/month/year.

**Comment by fx19880617** [comment]
cc @kishoreg @Jackie-Jiang @npawar

**Comment by kishoreg** [comment]
it's probably better to add new short udf instead of overloading existing udf. Do you have examples from other SQL engines for these operations?

**Comment by fx19880617** [comment]
sql use functions like `year()`/`month()`/`week()` to extract year from a given date.
RFE: https://prestodb.io/docs/current/functions/datetime.html
See: Extraction Function section.

**Comment by mr-agrwal** [comment]
I can take it up.

**Comment by fx19880617** [comment]
We may also want to support this as granular in `datetimeConvertUdf`, so that we can take the pushdown from presto side for function: `date_trunc`(https://prestodb.io/docs/current/functions/datetime.html).

|Unit | Example Truncated Value|
|-- | --|
|second | 2001-08-22 03:04:05.000
|minute | 2001-08-22 03:04:00.000
|hour | 2001-08-22 03:00:00.000
|day | 2001-08-22 00:00:00.000
|week | 2001-08-20 00:00:00.000
|month | 2001-08-01 00:00:00.000
|quarter | 2001-07-01 00:00:00.000
|year | 2001-01-01 00:00:00.000

```
The above examples use the timestamp 2001-08-22 03:04:05.321 as the input.

date_trunc(unit, x) → [same as input]
Returns x truncated to unit.
```
Currently we are missing `week`/`month`/`quarter`/`year`.

**Comment by deemoliu** [comment]
Hello @mr-agrwal, may I ask you about the ETA on this feature?

I am a Pinot user from Uber and we are looking for a solution to support the following Presto SQL.
I discussed with @fx19880617 and I believe your change on this ticket is required for supporting the below query.

`select
  date_trunc(
    'week',
    cast(eater_request_datestr_local as date)
  ) as datestr,
  sum(item_sales_local)
from
  pinotprod.restaurant_bi_item_sold.restaurant_bi_item_sold
where
  eater_request_datestr_local >= '2020-07-24'
group BY
  1
`

**Comment by Jackie-Jiang** [comment]
@fx19880617 @deemoliu @mr-agrwal We recently merged this PR for more datetime support: https://github.com/apache/incubator-pinot/pull/5438
I think it covers the use cases in this ticket

**Comment by deemoliu** [comment]
Thanks a lot @Jackie-Jiang I will take a look and give it a try.

**Comment by fx19880617** [comment]
@deemoliu can you verify that your needs is satisfied with #5438 ?
We can then working on presto side to do query rewrite for this.

**Comment by fx19880617** [comment]
Fixing an issue which prevents using functions introduced in #5438
