### ISSUE TITLE
Standalone ingestion jobs do not clean up output files after completing loading

### ISSUE THREAD

**Issue by plaisted** [apache/incubator-pinot#6349]
When running an ingestion job using the 'standalone' execution framework, the files written to 'outputDirURI' persist after the job completes. A couple issues arise from this:

- This causes subsequent ingestion runs to add the left over files from previous runs in addition to the files for the current run
- If concurrent jobs are running with the same storage location they would attempt to load each others files

I haven't dug into the code but it seems like the job should:
- clean up after itself
- only load segments from the outPutDirURI that it created in the job

If there are reasons why it shouldn't / can't do this, additional documentation on the behavior / purpose of the outputDirURI with standalone jobs would be helpful to callout the cleanup / URI uniqueness requirements.

**Comment by amarnathkarthik** [comment]
@kishoreg @plaisted Please assign this task to me, I would like to work on this issue.

**Comment by amarnathkarthik** [comment]
Here is my analysis, Looked at `LaunchDataIngestionJobCommand.java` and it's all job runner (Segment Generator and Push job). Did not see implementation to clean up `outputDirURI` after the push but do see tempDir cleanup after copying the generated segments to outputDirURI.

@kishoreg @plaisted We have 2 option, let me know which one would be appropriate:

1. **Backward compatible** - Introduce new property in `SegmentGenerationJobSpec._cleanupOutputAfterPush` to remove segments from `outputDirURI` once after push call finishes successfully. CleanupOutputAfterPush can be configurable using yaml and default it to `false`
2. **Cleanup by default** - Enhance the push job to remove the segments from the outputDirURI once after push call finishes successfully.

Note: 
Both Spark and Hadoop push jobs does not support cleanup today.

**Comment by fx19880617** [comment]
1. For the ingestion job, it's by design to keep the segments in output directory. The reason is that for URI and METADATA push job, the output dir is treated at the source of truth of the segment. E.g. users will use this job to generate segments and directly write into s3, then push metadata to Pinot for loading segments from the same s3 directory. 

I think it's ok to add a config like `cleanUpOutputDir` to delete the output directory if the push mode is `TAR` and the default value should be false. 

2. We usually expect the ingestion job output directory to be empty, but you are right, if there are segments already there or building in progress, then it will push them all. 

To solve this I feel we can:
- Merge segment generation and push into one task;
- Let segment generation job return an array of generated tar file URIs
- Push task will take the array and do the work.

**Comment by amarnathkarthik** [comment]
@fx19880617 Thanks for the clarification and suggestion.

Shouldn't we just delete the files instead of deleting the output directory for both Tar and Uri push? Also, instead of merging the segment generation and push task, maybe add the cleanUp to remove the tar files from the output directory once push finishes similar to `SegmentMetadataPush`, this will eliminate removing incorrect segment file(s) generated by another job (s).

**Comment by amarnathkarthik** [comment]
@plaisted Could you please mark this issue closed? I do not see an option to close.

CC: @fx19880617

**Comment by plaisted** [comment]
Ty @amarnathkarthik will check the changes out

**Comment by fx19880617** [comment]
Thanks, @amarnathkarthik !!!

This is awesome!
