### ISSUE TITLE
Pinot Query Level Timeout

### ISSUE THREAD

**Issue by PangZhi** [apache/incubator-pinot#712]
Currently Pinot only has server level timeout, which means every time i want to change the timeout, i need to restart the server. This makes pinot not able to be used for both long & short queries. Query level timeout is needed.

**Comment by anujambekar** [comment]
+1

**Comment by mayankshriv** [comment]
We do have a mechanism to pass query specific parameters, for example, whether or not to use starTree index for a given query. Query specific timeouts can be easily passed in using the same mechanism.

**Comment by Jackie-Jiang** [comment]
Introduced a query config in table config: #5162 to define the timeout for a table
Query/table level timeout implementation: #5169 

In order to get the query level timeout, you may send the query with timeout in the query options with key: `timeoutMs`
In order to get the table level timeout, you may config it under the query config
